### ISSUE TITLE
提示以下错误，请问是版本问题么

### ISSUE THREAD

**Issue by qdyuanye** [Diaoxiaozhang/Ximalaya-XM-Decrypt#13]
Traceback (most recent call last):
  File "E:\Python\Pycharm\PyCharm_workspace\量化\ximalayajiemi\main.py", line 221, in <module>
    decrypt_xm_file(file, output_path)
  File "E:\Python\Pycharm\PyCharm_workspace\量化\ximalayajiemi\main.py", line 145, in decrypt_xm_file
    output = f"{output_path}/{replace_invalid_chars(info.album)}/{replace_invalid_chars(info.title)}.{find_ext(audio_data[:0xff])}"
  File "E:\Python\Pycharm\PyCharm_workspace\量化\ximalayajiemi\main.py", line 134, in find_ext
    value = magic.from_buffer(data).lower()
  File "E:\Python\Pycharm\PyCharm_workspace\量化\lib\site-packages\magic\magic.py", line 146, in from_buffer
    m = _get_magic_type(mime)
  File "E:\Python\Pycharm\PyCharm_workspace\量化\lib\site-packages\magic\magic.py", line 122, in _get_magic_type
    i = _instances[mime] = Magic(mime=mime)
  File "E:\Python\Pycharm\PyCharm_workspace\量化\lib\site-packages\magic\magic.py", line 71, in __init__
    magic_load(self.cookie, magic_file)
  File "E:\Python\Pycharm\PyCharm_workspace\量化\lib\site-packages\magic\magic.py", line 272, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
  File "E:\Python\Pycharm\PyCharm_workspace\量化\lib\site-packages\magic\magic.py", line 203, in errorcheck_negative_one
    raise MagicException(err)
magic.magic.MagicException: b'could not find any valid magic files!'

**Comment by Diaoxiaozhang** [comment]
检查是否正确安装python-magic-bin包并没有安装python-magic包

**Comment by qdyuanye** [comment]
![捕获](https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt/assets/87895202/fba51150-f388-41f8-839b-1f529a885c44)
已经安装python-magic-bin包，试了4.13版本和4.14版本都不行。

**Comment by Diaoxiaozhang** [comment]
试试开个新的虚拟环境？

**Comment by qdyuanye** [comment]
谢谢。我再试试看。
