### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Fanxing-9049** [Diaoxiaozhang/Ximalaya-XM-Decrypt#18]
解密路径和输出路径都设置好了 运行就闪退 然后什么都没有了
输出路径不设置也是一样的 不知道这是为什么
以管理员身份运行也是同样闪退

**Comment by Diaoxiaozhang** [comment]
用cmd运行，看看报错什么

**Comment by Fanxing-9049** [comment]
Traceback (most recent call last):
  File "main.py", line 221, in <module>
  File "main.py", line 145, in decrypt_xm_file
  File "main.py", line 134, in find_ext
  File "magic\magic.py", line 146, in from_buffer
  File "magic\magic.py", line 122, in _get_magic_type
  File "magic\magic.py", line 71, in __init__
  File "magic\magic.py", line 272, in magic_load
  File "magic\magic.py", line 203, in errorcheck_negative_one
magic.magic.MagicException: b'could not find any valid magic files!'
[56724] Failed to execute script 'main' due to unhandled exception!

**Comment by Fanxing-9049** [comment]
![image](https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt/assets/123940373/ecc5733e-f061-4dde-9c3a-cc092d0e3416)

**Comment by Diaoxiaozhang** [comment]
你是直接运行的exe吗？这个问题一般是发生在magic库没装对的情况下的，直接运行打包好的exe不应该发生这样的错误

**Comment by Fanxing-9049** [comment]
> 是直接运行的exe吗？这个问题一般是发生在magic库没有安装对的情况下的，直接运行你的压缩好的exe不应该发生这样的错误

是的，直接运行exe闪退，然后根据你说的cmd里操作提示这个错误！~这个有没有办法解决

**Comment by Diaoxiaozhang** [comment]
你要不试试用自己用python运行，你开个3.9版本的虚拟环境或者conda环境，把requirements装一下然后运行main.py
