### ISSUE TITLE
0.13版本，解密最新喜马拉雅客户端下载的xm音频时闪退

### ISSUE THREAD

**Issue by jzbqy** [Diaoxiaozhang/Ximalaya-XM-Decrypt#27]
0.13版本，解密最新喜马拉雅客户端下载的xm音频时闪退，Ximalaya-XM-Decrypt-v0.1.3.exe和xm_encryptor.wasm在同一文件夹，exe可以正常打开，但按照指引选择文件解密时，会百分百闪退，批量和单文件，指定和不指定路径都尝试过了，全部闪退

**Comment by Diaoxiaozhang** [comment]
请尝试使用cmd运行exe文件，然后把报错内容发过来

**Comment by jzbqy** [comment]
![1](https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt/assets/126179646/494179db-f8a1-4553-a8e4-bf2c4747a448)
如上，麻烦大佬了

**Comment by Diaoxiaozhang** [comment]
试试用自己用python运行，开个3.9版本的虚拟环境或者conda环境，把requirements装一下然后运行main.py

**Comment by gaosi65** [comment]
C:\Users\Administrator\Desktop\喜马拉雅\xm转换>Ximalaya-XM-Decrypt-v0.1.3.exe
欢迎使用喜马拉雅音频解密工具
本工具仅供学习交流使用，严禁用于商业用途
请选择您想要使用的功能：
1. 解密单个文件
2. 批量解密文件
3. 退出
2
请选择是否需要设置输出路径：（不设置默认为本程序目录下的output文件夹）
1. 设置输出路径
2. 不设置输出路径
2
正在解密C:/Users/Administrator/Music/喜马拉雅/CV声线展示专辑【天禄客栈广播剧社】\社员声线展示少女少御萝莉少年CV接新【珺 心未琢】.xm
Traceback (most recent call last):
  File "main.py", line 220, in <module>
  File "main.py", line 147, in decrypt_xm_file
  File "main.py", line 140, in find_ext
Exception: unexpected format audio file with id3 version 2.3.0
[3632] Failed to execute script 'main' due to unhandled exception!

C:\Users\Administrator\Desktop\喜马拉雅\xm转换>

**Comment by gurarpikt** [comment]
> ![1](https://github.com/Diaoxiaozhang/Ximalaya-XM-Decrypt/assets/126179646/494179db-f8a1-4553-a8e4-bf2c4747a448) 如上，麻烦大佬了，另外可不可以支持安卓喜马拉雅下载到本地的音频解密，目前是有其他可以解密音频的工具的，但是文件名也是加密的，音频解密了也不知道对应的分集
我重装系统以后，就出现了（magic.MagicException: b'could not find any valid magic files!'）闪退报错，后来发现是用户名中文路径导致的。解决办法，控制面板添加新的本地用户，用户名为英文或是非中文，然后用新用户登录系统就不会报错闪退了。原管理员用户名的文件夹最好别改。
