### ISSUE TITLE
[Bug] 喜马拉雅是文件格式可能发生变更

### ISSUE THREAD

**Issue by moleoxa** [Diaoxiaozhang/Ximalaya-XM-Decrypt#35]
Traceback (most recent call last):
  File "main.py", line 220, in <module>
  File "main.py", line 146, in decrypt_xm_file
  File "main.py", line 85, in xm_decrypt
  File "main.py", line 50, in get_xm_info
  File "mutagen\id3\_file.py", line 76, in __init__
  File "mutagen\id3\_tags.py", line 172, in __init__
  File "mutagen\_util.py", line 533, in __init__
  File "mutagen\_tags.py", line 110, in __init__
  File "mutagen\_util.py", line 184, in wrapper
  File "mutagen\_util.py", line 155, in wrapper
  File "mutagen\id3\_file.py", line 151, in load
  File "mutagen\_util.py", line 184, in wrapper
  File "mutagen\id3\_tags.py", line 66, in __init__
mutagen.id3._util.ID3NoHeaderError: '<unknown>' doesn't start with an ID3 tag
[16084] Failed to execute script 'main' due to unhandled exception!

**Comment by moleoxa** [comment]
打扰了，仔细瞧了眼，这应该不是针对 x3m 文件的项目。
