### ISSUE TITLE
转换无损格式的xm文件闪退报错

### ISSUE THREAD

**Issue by MXGMXG** [Diaoxiaozhang/Ximalaya-XM-Decrypt#41]
只有无损会闪退，同一集音频超高就不会闪退

日志：
正在解密C:/Users/18631/Music/喜马拉雅/三体（全六季）! 精品广播剧，刘慈欣著/《三体》第一季 第二集 射手和农场主.xm
FLAC, 1909.99 seconds, 48000 Hz (audio/flac)
encoder=Lavf58.76.100
title=《三体》第一季 第二集 射手和农场主
album=三体（全六季）| 精品广播剧，刘慈欣著
artist=三体宇宙
Traceback (most recent call last):
  File "main.py", line 220, in <module>
  File "main.py", line 156, in decrypt_xm_file
  File "mutagen\_util.py", line 184, in wrapper
  File "mutagen\_util.py", line 155, in wrapper
  File "mutagen\flac.py", line 850, in save
  File "mutagen\flac.py", line 854, in _save
  File "mutagen\flac.py", line 911, in __check_header
  File "mutagen\flac.py", line 68, in read
mutagen.flac.error: file said 4 bytes, read 0 bytes
[6676] Failed to execute script 'main' due to unhandled exception!

**Comment by GuryYu** [comment]
第156行注释掉就可以保存了
# tags.save(buffer)

**Comment by zhangxu368** [comment]
> 只有无损会闪退，同一集音频超高就不会闪退
> 
> 日志： 正在解密C:/Users/18631/Music/喜马拉雅/三体（全六季）! 精品广播剧，刘慈欣著/《三体》第一季 第二集 射手和农场主.xm FLAC, 1909.99 seconds, 48000 Hz (audio/flac) encoder=Lavf58.76.100 title=《三体》第一季 第二集 射手和农场主 album=三体（全六季）| 精品广播剧，刘慈欣著 artist=三体宇宙 Traceback (most recent call last): File "main.py", line 220, in File "main.py", line 156, in decrypt_xm_file File "mutagen_util.py", line 184, in wrapper File "mutagen_util.py", line 155, in wrapper File "mutagen\flac.py", line 850, in save File "mutagen\flac.py", line 854, in _save File "mutagen\flac.py", line 911, in __check_header File "mutagen\flac.py", line 68, in read mutagen.flac.error: file said 4 bytes, read 0 bytes [6676] Failed to execute script 'main' due to unhandled exception!

  同一专辑同样问题，不知道您搞定了吗，这个无损的音频还挺想要的。谢谢
