### ISSUE TITLE
Exception: unexpected format audio file with id3 version 2.4.0, contains:mpeg adts, layer iii, v2, 160 kbps, 24 khz, monaural

### ISSUE THREAD

**Issue by allanxia** [Diaoxiaozhang/Ximalaya-XM-Decrypt#5]
运行时出现下面这个错误，请问是怎么回事？

Traceback (most recent call last):
  File "/Users/Documents/Ximalaya-XM-Decrypt-main/main.py", line 221, in <module>
    decrypt_xm_file(file, output_path)
  File "/Users/Documents/Ximalaya-XM-Decrypt-main/main.py", line 145, in decrypt_xm_file
    output = f"{output_path}/{replace_invalid_chars(info.album)}/{replace_invalid_chars(info.title)}.{find_ext(audio_data[:0xff])}"
  File "/Users/Documents/Ximalaya-XM-Decrypt-main/main.py", line 138, in find_ext
    raise Exception(f"unexpected format {value}")
Exception: unexpected format audio file with id3 version 2.4.0, contains:mpeg adts, layer iii, v2, 160 kbps, 24 khz, monaural

**Comment by Diaoxiaozhang** [comment]
能提供一下你需要解密的xm文件和喜马拉雅声音链接吗
